defaults:
  - base_vlm_task
_target_: tasks.counting.Counting
task_name: 'counting_low_diversity' # Name of the task
n_objects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] # Number of objects in the display
n_trials: 100 # Number of trials to generate per condition
size: 28 # Size of the images
shape_inds: [100]
prompt_path: '${.root_dir}/prompts/counting_${.task_variant}.txt'