defaults:
  - base_vlm_task
_target_: tasks.search.DisjunctiveSearchControl
task_name: 'disjunctive_search_control' # Name of the task
n_objects: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50] # Number of objects in the display
n_trials: 100 # Number of trials to generate per condition
size: 22
shape_inds: [100]
prompt_path: '${.root_dir}/prompts/disjunctive_search_${.task_variant}_control.txt'