defaults:
  - base_vlm_task
_target_: tasks.scene_description.SceneDescription
task_name: 'scene_description' # Name of the task
n_objects: [10, 11, 12, 13, 14, 15] # Number of objects in the display
n_trials: 100 # Number of trials to generate per condition
size: 40 # Size of the images
color_names: ['red', 'magenta', 'salmon', 'green', 'lime', 'olive', 'blue', 'teal', 'gold', 'purple', 'saddlebrown', 'gray', 'black', 'cyan', 'darkorange']
shape_names: ['airplane', 'triangle', 'cloud', 'X-shape', 'umbrella', 'pentagon', 'heart', 'star', 'circle', 'square', 'spade', 'scissors', 'infinity', 'check mark', 'right-arrow']
shape_inds: [6, 9, 21, 24, 34, 59, 96, 98, 100, 101, 51, 60, 5, 85, 29]
prompt_path: '${.root_dir}/prompts/${.task_name}_${.task_variant}.txt'
